node_modules上書きされないように変更

diff --git a/front/Dockerfile b/front/Dockerfile
--- a/front/Dockerfile
+++ b/front/Dockerfile
@@ -1,7 +1,13 @@
-FROM node:18.17-alpine
-
+FROM node:20-alpine AS base
 
 WORKDIR /app
 
-COPY ./package.json ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
 RUN npm install
